TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = $(TOPDIR)\resource\graphics

.SUFFIXES: .bbg

BGFS = wolf.bgf wolfX.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	$(RM) $(CLIENTRUNDIR)\resource\wolf.bgf
	$(RM) $(CLIENTRUNDIR)\resource\wolfX.bgf

clean-frames:
	$(RM) *.bmp
