#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wand.bof
BOFS = blindw.bof holdw.bof brittlew.bof dementw.bof markdisw.bof enfblew.bof \
	forgetw.bof hospicew.bof identifw.bof purifyw.bof seducew.bof shatterw.bof \
	swapw.bof lightngw.bof slitherw.bof

!include $(KODDIR)\kod.mak
