# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = grd61001.bgf \
       grd61002.bgf \
       grd61003.bgf \
       grd61004.bgf \
       grd61005.bgf \
       grd61006.bgf \
       grd61007.bgf \
       grd61008.bgf \
       grd61009.bgf \
       grd61010.bgf \
       grd61011.bgf \
       grd61012.bgf \
       grd61013.bgf \
       grd61014.bgf \
       grd61015.bgf \
       grd61016.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\grd61001.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61002.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61003.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61004.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61005.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61006.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61007.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61008.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61009.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61010.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61011.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61012.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61013.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61014.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61015.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\grd61016.bgf 2>nul
