#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\objroom.bof
BOFS = forest1.bof tosinn.bof cave2.bof marinn.bof marsmith.bof marelder.bof \
        canyon2.bof canyon1.bof forest5.bof castle1.bof barlbar1.bof b6.bof \
        c5.bof c7.bof e6.bof h4.bof h9.bof icecave1.bof \
        duke4.bof duke5.bof k5.bof
#       o6.bof o7.bof o8.bof p8.bof p9.bof 

!include $(KODDIR)\kod.mak
