#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\ring.bof
BOFS = ringinv.bof lethring.bof besring.bof resring.bof \
       ringwedd.bof ringsgnt.bof ringreag.bof

!include $(KODDIR)\kod.mak
