#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\mask.bof
BOFS = antmask.bof kriipmsk.bof ratmask.bof skullmsk.bof trollmsk.bof \
       cowmask.bof daemmask.bof feymask.bof mummymsk.bof xeomask.bof \
       shrnkmsk.bof dratmask.bof strollmsk.bof

!include $(KODDIR)\kod.mak
