# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = ratsm.bgf ratsmX.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\ratsm.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\ratsmX.bgf 2>nul
