# makefile for skyboxen

TOPDIR=..\..\..
!include $(TOPDIR)\common.mak

all:
	@-copy /b /y skye-east.png+skye-under.png+skye-west.png+skye-north.png+skye-south.png+skye-above.png skye.bsf > nul

clean:
	@-$(RM) skye.bsf
