#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\hstone.bof
BOFS = hstonred.bof hstonblu.bof hstonsky.bof hstonbrn.bof \
       hstongre.bof hstonblk.bof hstonwht.bof hstondkgre.bof \
       hstonpurp.bof

!include $(KODDIR)\kod.mak
