#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\rod.bof
BOFS = healrod.bof vamprod.bof joltrod.bof \
	spellrod.bof shieldrod.bof damagerod.bof \
    breakrodpurge.bof breakrodhold.bof breakrodblind.bof

!include $(KODDIR)\kod.mak
