call build blessico.bgf
call build nitvsico.bgf
call build iacidtou.bgf
call build ianimate.bgf
call build ianonym.bgf
call build ianonymo.bgf
call build iantimag.bgf
call build iapparit.bgf
call build iartific.bgf
call build ibetraya.bgf
call build iblind.bgf
call build iboonagi.bgf
call build iboonaim.bgf
call build iboonint.bgf
call build iboonmig.bgf
call build iboonmys.bgf
call build iboonsta.bgf
call build ibrittle.bgf
call build icamofla.bgf
call build icanniba.bgf
call build icespflt.bgf
call build icounter.bgf
call build icrefood.bgf
call build icremace.bgf
call build icuredis.bgf
call build icurpoi.bgf
call build icursed.bgf
call build icurswpn.bgf
call build idarknes.bgf
call build ideathli.bgf
call build idefile.bgf
call build idement.bgf
call build idenial.bgf
call build idetevil.bgf
call build idetgood.bgf
call build idetinvi.bgf
call build idiscord.bgf
call build idiseasd.bgf
call build idispill.bgf
call build idistrac.bgf
call build ienchant.bgf
call build ienfeebl.bgf
call build ifade.bgf
call build ifirebal.bgf
call build iflash.bgf
call build ifog.bgf
call build iforesig.bgf
call build iforget.bgf
call build ifrclite.bgf
call build igort.bgf
call build ihaste.bgf
call build iheal.bgf
call build iheat.bgf
call build ihold.bgf
call build iholyres.bgf
call build iholyt.bgf
call build iholywpn.bgf
call build ihospice.bgf
call build iicyfing.bgf
call build iidentif.bgf
call build iillufrm.bgf
call build iilluwou.bgf
call build iinvisib.bgf
call build ikarahol.bgf
call build ikillfel.bgf
call build ilagbox.bgf
call build ilitning.bgf
call build imajheal.bgf
call build imanabom.bgf
call build imanafoc.bgf
call build imarkdis.bgf
call build imartyrs.bgf
call build imend.bgf
call build imorph.bgf
call build invcirc.bgf
call build invisibl.bgf
call build iparalyz.bgf
call build ipersona.bgf
call build ipoiscld.bgf
call build iposoned.bgf
call build ipurify.bgf
call build iqorbane.bgf
call build irasdead.bgf
call build iraylite.bgf
call build ireflect.bgf
call build iremcurs.bgf
call build irescold.bgf
call build iresfire.bgf
call build iresgood.bgf
call build iresmagc.bgf
call build irespois.bgf
call build iresshok.bgf
call build ireveal.bgf
call build irthquak.bgf
call build isandsto.bgf
call build iseduce.bgf
call build ishabane.bgf
call build ishadfrm.bgf
call build ishatter.bgf
call build ishroud.bgf
call build isilence.bgf
call build islither.bgf
call build ispebane.bgf
call build ispirith.bgf
call build isporecl.bgf
call build istreng.bgf
call build isunlite.bgf
call build iswap.bgf
call build ithorns.bgf
call build itoucfla.bgf
call build itruce.bgf
call build itruth.bgf
call build iumbrela.bgf
call build iunholyw.bgf
call build ivamptou.bgf
call build ivertigo.bgf
call build iwalfire.bgf
call build iwallfla.bgf
call build iwallill.bgf
call build iwalltho.bgf
call build iwarptim.bgf
call build iwinds.bgf
call build izap.bgf
