#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\active.bof
BOFS = holder.bof portal.bof poscache.bof spidtree.bof logghost.bof hotplate.bof \
	listener.bof flag.bof wallelem.bof radiustotem.bof


!include $(KODDIR)\kod.mak
