#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\marntwn.bof
BOFS  = mrurchin.bof mrinnk.bof mrsmith.bof mrelder.bof mrbart.bof mrhealer.bof

!include $(KODDIR)\kod.mak
