#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\itemench.bof
BOFS = artifice.bof enchwp.bof glow.bof holywp.bof identify.bof \
       mend.bof reveal.bof shroud.bof unholywp.bof

!include $(KODDIR)\kod.mak
