#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\specwand.bof
BOFS = healwand.bof firewand.bof vampwand.bof joltstaf.bof bonkstik.bof \
	spelwand.bof

!include $(KODDIR)\kod.mak
