#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jala.bof
BOFS = spelbane.bof warptime.bof manaconv.bof jig.bof hinder.bof \
       invigor.bof restorat.bof rejuven.bof mirth.bof melcholy.bof

!include $(KODDIR)\kod.mak
