#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\flikerer.bof
BOFS = candle.bof tablamp.bof skullbrz.bof orctorch.bof koclamp.bof smoke.bof \
	brazier.bof lamp.bof firepit.bof candelab.bof kocbraz.bof dynlight.bof \
	glowtree.bof bswitch.bof

!include $(KODDIR)\kod.mak
