#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\bountyquest.bof
BOFS = monsterbounty.bof itembounty.bof returnbounty.bof builderbounty.bof

!include $(KODDIR)\kod.mak
