#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\barlqrm.bof

BOFS =  barln.bof barls.bof barapoth.bof barhall.bof barinn.bof barlport.bof \
	gmhall.bof barmerch.bof asshq.bof barsmith.bof barvault.bof \
	barcourt.bof barjail.bof

!include $(KODDIR)\kod.mak

