#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\questitem.bof
BOFS = avarfeth.bof chiksoup.bof cncllttr.bof dresspat.bof formula.bof\
   lablpot.bof lablwand.bof letter.bof lovelttr.bof mystpot.bof mystwand.bof\
   ncwrnlet.bof neclettr.bof potaphro.bof recipe.bof sachaqua.bof\
   scamscrl.bof taxlettr.bof warlettr.bof srsttkn.bof\

!include $(KODDIR)\kod.mak
