#define Contents 1
#define INTRODUCTION 2
#define Installing_WindDEU 3
#define WINDEU_FEATURES 4
#define STARTING_WINDEU 5
#define CMD_LINE_PARAMS 6
#define Preferences_settings 7
#define WINDEU_INI 8
#define Main_menu 9
#define FILE_POPUP 10
#define Open_WAD_file 11
#define Save_object 12
#define Build_new_main 13
#define Group_WAD_files 14
#define Insert_RAW_file 15
#define Extract_object 16
#define List_master_directory 17
#define Master_directory 18
#define List_opened_WAD_files 19
#define List_of_WAD_files 20
#define Entries_of_selected_file 21
#define Show_levels_only 22
#define Exit 23
#define EDITOR_POPUP 24
#define Edit_level 25
#define Create_level 26
#define Dump_entry 27
#define Entries 28
#define Hexadecimal_dump 29
#define View_Sprites 30
#define View_Wall_textures 31
#define View_Floor_Ceiling_textures 32
#define Selecting_level_to_edit 33
#define Doom_2 34
#define Episode_number 35
#define Mission_number 36
#define Doom_2_map_number 37
#define Viewing_pictures 38
#define Select_picture_name 39
#define Picture_display 40
#define Select_zoom_factor 41
#define Select_gamma_correction 42
#define Level_editor 43
#define KEYBOARD_REF 44
#define Quit_key 45
#define Escape_key 46
#define Scroll_lock_key 47
#define Space_key 48
#define Zoom_keys 49
#define Change_edit_mode_keys 50
#define Jump_to_object_keys 51
#define Mark_objects_keys 52
#define Copy_object_keys 53
#define Insert_object_keys 54
#define Delete_object_key 55
#define Grid_keys 56
#define Edit_key 57
#define Info_bar_key 58
#define Ruler_cursor_key 59
#define Ctrl_key 60
#define Help_key 61
#define Save_keys 62
#define Search_key 63
#define Preferences_key 64
#define Mouse_Commands 65
#define MENU_BAR 66
#define EDITOR_File 67
#define EDITOR_Save 68
#define EDITOR_Save_as 69
#define Quit_editor 70
#define Edit 71
#define Edit_Undo 72
#define Edit_Redo 73
#define Edit_objects 74
#define Copy_objects 75
#define Add_object 76
#define Insert_standard_object 77
#define Insert_Rectangle 78
#define Insert_Polygon 79
#define Delete_objects 80
#define Preferences 81
#define Wall_textures_list 82
#define Default_upper_texture 83
#define Transfer_default_upper_texture 84
#define Default_normal_texture 85
#define Transfer_default_normal_texture 86
#define Default_lower_texture 87
#define Transfer_default_lower_texture 88
#define Clear_default_texture 89
#define Floor_Ceiling_textures_list 90
#define Default_floor_texture 91
#define Transfer_default_floor_texture 92
#define Default_floor_height 93
#define Default_ceiling_texture 94
#define Transfer_default_ceiling_texture 95
#define Default_ceiling_height 96
#define Default_Builder_priority 97
#define Default_Split_factor 98
#define Default_Debug_option 99
#define Default_Quiet_option 100
#define Default_Quieter_option 101
#define Default_Expert_mode_option 102
#define Default_Info_bar_option 103
#define Default_Additive_selection_box_option 104
#define Default_Select_0_option 105
#define Insert_Torch 106
#define Default_Draw_LineDef_length_option 107
#define Default_Maximum_undo 108
#define Search 109
#define Find_and_change 110
#define Repeat_last_find 111
#define Next_object 112
#define Previous_object 113
#define Jump_to_object 114
#define Miscelaneous 115
#define Free_tag_number 116
#define Things_miscelaneous 117
#define Rotate_and_scale_Things 118
#define Vertices_miscelaneous 119
#define Rotate_and_scale_Vertices 120
#define Delete_Vertex_and_join_LineDefs 121
#define Merge_several_Vertices_into_one 122
#define Add_a_LineDef_and_split_Sector 123
#define LineDefs_and_SideDefs_miscelaneous 124
#define Rotate_and_scale_LineDefs 125
#define Split_LineDef_and_Add_new_Vertex 126
#define Split_LineDefs_and_Sectors 127
#define Delete_LineDefs_and_join_Sectors 128
#define Flip_LineDef 129
#define Swap_SideDefs 130
#define Align_textures_Y_offset 131
#define Align_textures_X_offset 132
#define SideDef_1_Check_name 133
#define SideDef_1_Check_name_and_initial_offset 134
#define SideDef_1_Do_not_Check_name 135
#define SideDef_1_Do_not_Check_name_and_Initial_offset 136
#define SideDef_2_Check_name 137
#define SideDef_2_Check_name_and_Initial_offset 138
#define SideDef_2_Do_not_Check_name 139
#define SideDef_2_Do_not_Check_name_and_Initial_offset 140
#define Sectors_miscelaneous 141
#define Rotate_and_scale_Sectors 142
#define Make_door_from_Sector 143
#define Make_lift_from_Sector 144
#define Distribute_Sector_floor_heights 145
#define Distributes_Sector_ceiling_heights 146
#define Modes 147
#define Things_edit_mode 148
#define Thing_X_position 149
#define Thing_Y_position 150
#define Thing_type_set 151
#define Thing_type 152
#define Thing_appearence_attributes 153
#define Thing_angle 154
#define Thing_preview 155
#define Confirming_copy_of_Thing_attributes 156
#define Copy_thing_attributes 157
#define LineDefs_edit_mode 158
#define LineDef_flags 159
#define LineDef_type_set 160
#define LineDef_type 161
#define LineDef_sector_tag 162
#define LineDef_new_sector_tag 163
#define LineDef_vertex_number 164
#define LineDef_SideDef_number 165
#define LineDef_new_SideDef 166
#define SideDef_x_offset 167
#define SideDef_y_offset 168
#define SideDef_sector_number 169
#define SideDef_above_wall 170
#define SideDef_normal_wall 171
#define SideDef_below_wall 172
#define Clear_SideDef_texture_name 173
#define Transfer_SideDef_texture_name 174
#define SideDef_texture_names 175
#define Confirming_copy_of_LineDef_attributes 176
#define Copy_LineDef_attributes 177
#define Copy_SideDef_attributes 178
#define Copy_LineDef_flags 179
#define Vertices_edit_mode 180
#define Vertex_X_position 181
#define Vertex_Y_position 182
#define Confirming_copy_of_Vertex_attributes 183
#define Copy_vertex_attributes 184
#define Sectors_edit_mode 185
#define Sector_special 186
#define Light_level 187
#define LineDef_tag 188
#define New_LineDef_tag 189
#define Floor_and_Ceiling_textures_list 190
#define Floor_texture 191
#define Clear_Floor_texture 192
#define Transfer_Floor_texture 193
#define Floor_height 194
#define Ceiling_texture 195
#define Clear_Ceiling_texture 196
#define Transfer_Ceiling_texture 197
#define Ceiling_height 198
#define Confirming_copy_of_Sector_attributes 199
#define Copy_sector_attributes 200
#define Next_mode 201
#define Previous_mode 202
#define Check 203
#define Display_statistics 204
#define Check_all_sectors_are_closed 205
#define Check_all_cross_references 206
#define Check_for_missing_textures 207
#define Check_textures_names 208
#define Window_popup 209
#define Center_Map 210
#define Zoom_In 211
#define Zoom_Out 212
#define Snap_to_grid 213
#define Show_grid 214
#define Increase_grid_scale 215
#define Decrease_grid_scale 216
#define Show_info_windows 217
#define Show_tool_bar 218
#define Show_info_bar 219
#define Info_windows_layout 220
#define Horizontal_down_left 221
#define Horizontal_down_right 222
#define Horizontal_up_left 223
#define Horizontal_up_right 224
#define Vertical_down_left 225
#define Vertical_down_right 226
#define Vertical_up_left 227
#define Vertical_up_right 228
#define Layout_now 229
#define Automatic_layout 230
#define Help 231
#define Help_contents 232
#define Search_help_on 233
#define Using_help 234
#define HELP_Keyboard 235
#define HELP_Mouse 236
#define HELP_Level_editor 237
#define HELP_Tutorial 238
#define About_WinDEU 239
#define WAD_FILE 240
#define VERTICES_DESCR 241
#define LINEDEFS_DESCR 242
#define SIDEDEFS_DESCR 243
#define SECTORS_DESCR 244
#define THINGS_DESCR 245
#define LINEDEF_ATTRIBUTES 246
#define Types_of_LineDefs 247
#define NOUPLO_TEXTURES 248
#define SPECIAL_DOOM_AREAS 249
#define DOORS 250
#define LIFTS 251
#define Teleporters 252
#define Rising_stairs 253
#define Secret_areas 254
#define Standard_rooms 255
#define TRY_NEW_LEVELS 256
#define TROUBLESHOOTING 257
#define HOM_EFFECT 258
#define WinDEU_bug 259
#define DOOM_RELAX 260
#define Tutorial 261
#define Making_your_first_level 262
#define Step_1 263
#define Step_2 264
#define Step_3 265
#define Step_4 266
#define Step_5 267
#define Step_6 268
#define Step_7 269
#define Step_8 270
#define Step_9 271
#define Step_10 272
#define Step_11 273
#define Step_12 274
#define Step_13 275
#define Step_14 276
#define Adding_a_door 277
#define Door_step_1 278
#define Door_step_2 279
#define Adding_a_stairway 280
#define Stairway_step_1 281
#define Stairway_step_2 282
#define Stairway_step_3 283
#define Stairway_step_4 284
#define Adding_a_lift 285
#define Lift_step_1 286
#define Lift_step_2 287
#define Lift_step_3 288
#define Lift_step_4 289
#define Lift_step_5 290
#define Lift_step_6 291
#define Lift_step_7 292
#define Lift_step_8 293
#define Lift_step_9 294
#define Adding_a_transporter 295
#define Transporter_step_1 296
#define Transporter_step_2 297
#define Transporter_step_3 298
#define Transporter_step_4 299
#define Transporter_step_5 300
#define Transporter_step_6 301
#define Texture_alignment_basis 302
#define Complex_texture_alignment 303
#define Upper_and_lower_textures_alignment 304
#define Tips 305
#define Editing_tips 306
#define DOOM_LIMITS 307
#define Insert_Circle 308
#define Align_textures_X_circle 309
