#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\desert.bof

BOFS = desertpath1.bof desertdunes.bof desertcliffaccess.bof waylayoasis.bof \
       desertcliffnoaccess1.bof desertcliffnoaccess2.bof \
       desertcliffnoaccess3.bof desertshore1.bof desertshore2.bof \
       desertshore3.bof desertriver1.bof desertriver2.bof

!include $(KODDIR)\kod.mak
