#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\itematt.bof
BOFS = weapatt.bof iacorptr.bof iadurabl.bof iatransc.bof \
                iashroud.bof iaengrav.bof iamisdir.bof iaselinf.bof \
                ianewdsc.bof iaappdsc.bof iaquest.bof iapkptr.bof \
				iabonded.bof iamade.bof iabond2.bof iarename.bof iasbind.bof

!include $(KODDIR)\kod.mak
