#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\ammo.bof
BOFS = arrow.bof bolt.bof slvarrow.bof neruarow.bof firearow.bof icearrow.bof \
         acidarow.bof goldarrow.bof

!include $(KODDIR)\kod.mak
