#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jasperrm.bof

BOFS =  jasper.bof jaswest.bof\
	jaselder.bof jashall.bof jasinn.bof jassmith.bof \
	jasstore.bof jastavrn.bof jasbank.bof \
	jasab1.bof jasab2.bof jasab3.bof jasab4.bof jasab5.bof jasab6.bof jasab7.bof \
	jasab8.bof jasab9.bof jasab10.bof jasab11.bof jasab12.bof jasab13.bof jasab14.bof \
	jasvault.bof

!include $(KODDIR)\kod.mak

