#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\gemresist.bof
BOFS = gemcoldres.bof gemshockres.bof gemacidres.bof gemthrustres.bof gempierceres.bof gemslashres.bof gembludgeonres.bof \
       gemfireres.bof

!include $(KODDIR)\kod.mak