#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\feyforst.bof

BOFS =   a1.bof b1.bof \
         b2.bof c1.bof c2.bof c3.bof d1.bof d2.bof

!include $(KODDIR)\kod.mak

