#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\scroll.bof
BOFS = mrtrscrl.bof lghtscrl.bof darkscrl.bof discscrl.bof \
      disilscl.bof earthscl.bof firitscl.bof flashscl.bof \
      heatscrl.bof killfscl.bof lghtscrl.bof \
      mrtrscrl.bof pfogscrl.bof sporescl.bof trucescl.bof \
      windscrl.bof

!include $(KODDIR)\kod.mak
