//
// OWLext
//
/// \file version.h
/// Library version and build information header
//
// Copyright (c) 2013 Vidar Hasfjord
// See OWLNext for license information (http://owlnext.sourceforge.net).

#if !defined(OWLEXT_VERSION_H)
#define OWLEXT_VERSION_H

#include <owl/version.h>

// Create aliases for OWL version macros
//
#define OWLEXT_PRERELEASE OWL_PRERELEASE
#define OWLEXT_FILEVERSION OWL_FILEVERSION
#define OWLEXT_PRODUCTVERSION OWL_PRODUCTVERSION
#define OWLEXT_FILEVERSION_STRING OWL_FILEVERSION_STRING
#define OWLEXT_PRODUCTVERSION_STRING OWL_PRODUCTVERSION_STRING
#define OWLEXT_VERSION_16BIT OWL_VERSION_16BIT
#define OWLEXT_VERSION_32BIT OWL_VERSION_32BIT
#define OWLEXT_VERSION_64BIT OWL_VERSION_64BIT
#define OWLEXT_BUILD_REVISION OWL_BUILD_REVISION
#define OWLEXT_BUILD_REVISION_DATE OWL_BUILD_REVISION_DATE
#define OWLEXT_BUILD_DATE OWL_BUILD_DATE
#define OWLEXT_BUILD_MIXED OWL_BUILD_MIXED
#define OWLEXT_BUILD_DIRTY OWL_BUILD_DIRTY

#endif  //  OWLEXT_VERSION_H
