#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weapon.bof
BOFS = shrtswrd.bof mystswrd.bof mace.bof bkdagger.bof spirhamm.bof\
        scimitar.bof longswrd.bof hammer.bof ranged.bof axe.bof goldswrd.bof \
        riijaswd.bof neruswd.bof huntsw.bof unique.bof testswrd.bof

!include $(KODDIR)\kod.mak
