#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weapon.bof
BOFS = bkdagger.bof ranged.bof huntsw.bof unique.bof \
       striking.bof slashing.bof thrusting.bof touching.bof

!include $(KODDIR)\kod.mak