# makefile for skyboxen

TOPDIR=..\..\..
!include $(TOPDIR)\common.mak

all:
	@-copy /b /y redsky1.png+redsky2.png+redsky3.png+redskyd.png+redskyd.png+redsky6.png redsky.bsf > nul

clean:
	@-$(RM) redsky.bsf
