#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\stroke.bof
BOFS = slash.bof unarmed.bof thrust.bof fire.bof strike.bof bash.bof riposte.bof touch.bof

!include $(KODDIR)\kod.mak
