#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\necklace.bof
BOFS = shadowam.bof qrcharm.bof krcharm.bof shcharm.bof rjcharm.bof frcharm.bof

!include $(KODDIR)\kod.mak
