#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\brain.bof
BOFS = revbrain.bof blindb.bof paralyze.bof guardb.bof karmaagg.bof nonagg.bof \
       swarmbrain.bof

!include $(KODDIR)\kod.mak
