#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\brain.bof
#BOFS = revbrain.bof blindb.bof paralyze.bof guardb.bof karmaagg.bof nonagg.bof
BOFS = brain2.bof

!include $(KODDIR)\kod.mak
