# makefile for skyboxen

TOPDIR=..\..\..
!include $(TOPDIR)\common.mak

all:
	@copy /b skya-east.png+skya-under.png+skya-west.png+skya-north.png+skya-south.png+skya-above.png skya.bsf > nul

clean:
	@-$(RM) skya.bsf
