#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\offering.bof
BOFS = offerrii.bof offerkra.bof offersha.bof offerqor.bof offerfar.bof                                  

!include $(KODDIR)\kod.mak
