//----------------------------------------------------------------------------
//  Project ced
//  OWL NExt
//  Copyright 2000. All Rights reserved.
//
//  SUBSYSTEM:    ced Application
//  FILE:         hexdocument.h
//  AUTHOR:       Yura
//
//  OVERVIEW
//  ~~~~~~~~
//  Class definition for THexDocument (TDocument).
//  (Generated by OWL 6.x Class Expert for MS VC++, Version 1.5)
//----------------------------------------------------------------------------
#if !defined(COOL_HEXDOCUMENT_H) // Sentry, use file only if it's not already included.
#define COOL_HEXDOCUMENT_H

#include <owl\docview.h>
#include <coolprj/hexedit.h>

//{{TDocument = THexDocument}}
class _COOLCLASS THexDocument: public owl::TDocument {
  public:
    THexDocument(owl::TDocument* parent = 0);
    virtual ~THexDocument ();

    THexFileBuffer& GetHexBuffer(){ return Buffer; }

  protected:
    THexFileBuffer Buffer;

  public:
    virtual bool Open(int mode, LPCTSTR path=0);
    virtual bool IsOpen();
    virtual bool IsDirty();
    virtual bool Commit(bool force=false);
    virtual bool Revert(bool clear=false);
}; 
inline bool THexDocument::IsOpen(){
  return Buffer.GetDataSize() != 0;
}


#endif  // COOL_HEXDOCUMENT_H sentry.

