# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = qormastree.bgf qormastreebig.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\qormastree.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\qormastreebig.bgf 2>nul
