// Meridian 59, Copyright 1994-2012 Andrew Kirmse and Chris Kirmse.
// All rights reserved.
//
// This software is distributed under a license that is described in
// the LICENSE file that accompanies it.
//
// Meridian is a registered trademark.
/* 
 * maketrig.c: Automatically generate .c and .h file containing discrete trig tables.
 */

#include <stdio.h>
#include <math.h>
#include <process.h>
#include "fixedpt.h"
#include "drawdefs.h"

static char progname[] = "MAKETRIG";
static char header_file[] = "trig.h";
static char table_file[] = "trig.c";

void usage(void)
{
   printf("usage: maketrig <output directory>\n");
   exit(1);
}

void file_error(void)
{
   printf("Error opening output file.  Exiting.\n");
   exit(1);
}

int discrete_log(long num)
{
   long i = 0, x = 1;

   while (x < num)
   {
      x <<= 1;
      i++;
   }

   return i;
}

int main(int argc, char **argv)
{
   int num_degrees, angle;
   FILE *headerfile, *tablefile;
   double radians;
   fix result;
   char tempbuf[512], *dir;
   int viewer_distance, maxx;

   if (argc != 2)
      usage();

   dir = argv[1];

   num_degrees = NUMDEGREES;
   maxx = MAXX;
   viewer_distance = VIEWER_DISTANCE;

   /* First spew the header file */
   sprintf(tempbuf, "%s\\%s", dir, header_file);
   headerfile = fopen(tempbuf, "wt");

   if (headerfile == NULL)
      file_error();

   fprintf(headerfile, "/*\n");
   fprintf(headerfile, " * %s: Header file for trig tables.\n", header_file);
   fprintf(headerfile, " * This file was automatically generated by %s.\n", progname);
   fprintf(headerfile, " */\n\n");
   fprintf(headerfile, "#ifndef _TRIG_H\n");
   fprintf(headerfile, "#define _TRIG_H\n\n");
   fprintf(headerfile, "#define NUMDEGREES %d\n", num_degrees);
   fprintf(headerfile, "#define LOG_NUMDEGREES %d\n", discrete_log(num_degrees));
   fprintf(headerfile, "#define COS(x) (cos_table[x & (NUMDEGREES - 1)])\n");
   fprintf(headerfile, "#define SIN(x) (sin_table[x & (NUMDEGREES - 1)])\n");
//   fprintf(headerfile, "#define TAN(x) (tan_table[x & (NUMDEGREES - 1)])\n");
//   fprintf(headerfile, "#define COT(x) (cot_table[x & (NUMDEGREES - 1)])\n");
   fprintf(headerfile, "\n");
   fprintf(headerfile, "extern long cos_table[NUMDEGREES];\n");
   fprintf(headerfile, "extern long sin_table[NUMDEGREES];\n");
//   fprintf(headerfile, "extern long tan_table[NUMDEGREES];\n");
//   fprintf(headerfile, "extern long cot_table[NUMDEGREES];\n");
//   fprintf(headerfile, "extern long atan_table[%d];\n", maxx);
   fprintf(headerfile, "\n#endif /* ifndef _TRIG_H */\n");

   fclose(headerfile);

   /* Now write out the tables themselves */
   sprintf(tempbuf, "%s\\%s", dir, table_file);
   tablefile = fopen(tempbuf, "wt");

   if (tablefile == NULL)
      file_error();

   fprintf(tablefile, "/*\n");
   fprintf(tablefile, " * %s: Trig tables.\n", table_file);
   fprintf(tablefile, " * This file was automatically generated by %s.\n", progname);
   fprintf(tablefile, " */\n");
   fprintf(tablefile, "#include \"client.h\"\n\n");

   /* cosine table */
   fprintf(tablefile, "long cos_table[%d] = {\n", num_degrees);

   for (angle = 0; angle < num_degrees; angle++)
   {
      radians = (double) angle * PITWICE / num_degrees;

      result = FloatToFix(cos(radians));
      
      fprintf(tablefile, "(long)0x%8.8x, ", result);

      if (angle % 4 == 3)
	 fprintf(tablefile, "\n");
   }

   fprintf(tablefile, "\n};\n\n");


   /* sine table */
   fprintf(tablefile, "long sin_table[%d] = {\n", num_degrees);

   for (angle = 0; angle < num_degrees; angle++)
   {
      radians = (double) angle * PITWICE / num_degrees;

      result = FloatToFix(sin(radians));
      
      fprintf(tablefile, "(long)0x%8.8x, ", result);

      if (angle % 4 == 3)
	 fprintf(tablefile, "\n");
   }

   fprintf(tablefile, "\n};\n\n");

// Tangent and cotangent tables no longer needed 9/95 ARK
// Arctangent table no longer needed 12/95 ARK
#if 0
   /* tangent table */
   fprintf(tablefile, "long tan_table[%d] = {\n", num_degrees);

   for (angle = 0; angle < num_degrees; angle++)
   {
      radians = (double) angle * PITWICE / num_degrees;

      /* Watch out for pi/2 and -pi/2 */
      if (angle == num_degrees / 4)
	 result = BIGFIXINT;
      else if (angle == num_degrees / 4 * 3)
	 result = -BIGFIXINT;
      else result = FloatToFix(tan(radians));

      if (result > BIGFIXINT)
	 result = BIGFIXINT;
      if (result < -BIGFIXINT)
	 result = -BIGFIXINT;

      fprintf(tablefile, "0x%8.8x, ", result);

      if (angle % 4 == 3)
	 fprintf(tablefile, "\n");
   }

   fprintf(tablefile, "\n};\n\n");

   /* cotangent table */
   fprintf(tablefile, "long cot_table[%d] = {\n", num_degrees);

   for (angle = 0; angle < num_degrees; angle++)
   {
      radians = (double) angle * PITWICE / num_degrees;

      /* Watch out for 0 and pi */
      if (angle == 0)
	 result = BIGFIXINT;
      else if (angle == num_degrees / 2)
	 result = BIGFIXINT;
      else result = FloatToFix(1.0 / tan(radians));

      if (result > BIGFIXINT)
	 result = BIGFIXINT;
      if (result < -BIGFIXINT)
	 result = -BIGFIXINT;
      
      fprintf(tablefile, "0x%8.8x, ", result);

      if (angle % 4 == 3)
	 fprintf(tablefile, "\n");
   }

   fprintf(tablefile, "\n};\n\n");

   /* Arctangent table */
   fprintf(tablefile, "long atan_table[%d] = {\n", maxx);

   for (i = 0; i < maxx; i++)
   {
      radians = atan(((double)(i - maxx / 2)) / viewer_distance);
      /* Convert radians to pseudodegrees */
      result = (long) ((radians * num_degrees) / PITWICE);
      if (result < 0)
	 result += num_degrees;

      fprintf(tablefile, "%4d, ", result);
      if (i % 8 == 7)
	 fprintf(tablefile, "\n");
   }
   fprintf(tablefile, "\n};\n\n");

   fclose(tablefile);
#endif

   return 0;
}
