//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by client.rc
//
#define IDS_CANTINITSOCKET              1
#define IDS_CANTWRITE                   2
#define IDS_COMERROR                    3
#define IDOK2                           3
#define IDS_MESSAGETOOLONG              4
#define IDCANCEL2                       4
#define IDS_READOVERFLOW                5
#define IDS_NOHOSTNAME                  6
#define IDS_NOPORTNUM                   7
#define IDS_UNKNOWNRESOURCE             8
#define IDS_ONEINSTANCE                 8
#define IDS_NOSERVERNUM                 8
#define IDS_MISSINGRESOURCE             9
#define IDS_NOROOMFILE                  10
#define IDS_ERRORRESOURCE               11
#define IDS_DUPRESOURCE                 12
#define IDS_SOCKETOPEN                  13
#define IDS_LOSTSERVER                  14
#define IDS_SOCKETMESSAGE               15
#define IDS_DOWNLOADALL                 17
#define IDS_CONFIGMENUEXE               18
#define IDS_CANTDELETEFILE              19
#define IDS_CANTWRITEFILE               20
#define IDS_UPLOADMSG                   21
#define IDS_NOCONFIGMENUEXE             21
#define IDS_VERSIONERROR                23
#define IDS_CONNECTERROR                24
#define IDS_BADLOGIN                    25
#define IDS_NOTIMERS                    26
#define IDS_ACCOUNTUSED                 27
#define IDS_SYSTEMDOWN                  28
#define IDS_TOOMANYLOGINS               29
#define IDS_TIMEOUT                     30
#define IDS_CANTRENAME                  31
#define IDS_NOGAME                      32
#define IDS_NOCREDITS                   33
#define IDS_PASSWDMATCH                 34
#define IDS_PASSWDLENGTH                35
#define IDS_PASSWDOK                    36
#define IDS_PASSWDNOTOK                 37
#define IDS_ABORTTRANSFER               38
#define IDS_ANNOTATIONSFULL             39
#define IDS_UNKNOWN                     41
#define IDS_EMPTY                       42
#define IDS_CRCERROR                    44
#define IDS_GOTOFFER                    45
#define IDS_WAITRESPONSE                46
#define IDS_QUIT                        49
#define IDS_INVENTORY                   50
#define IDS_LOGOFF                      51
#define IDS_INUSE                       52
#define IDS_MENUGAME                    53
#define IDS_EXEFILTER                   53
#define IDS_AGELESS                     53
#define IDS_GETCLIENT                   54
#define IDS_PASSWORDNOTCHANGED          54
#define IDS_GETRSC                      55
#define IDS_UPLOAD                      56
#define IDS_CHPASSWD                    57
#define IDS_ADMIN                       58
#define IDS_REGISTER                    59
#define IDS_ADMINNOTE                   60
#define IDS_HELP                        61
#define IDS_MENULOGOFF                  62
#define IDS_PASSWORDCHANGED             63
#define IDS_ADDRESS                     64
#define IDS_PHONENUM                    65
#define IDS_NAME                        66
#define IDS_NOREGISTER                  67
#define IDS_CHARNAME                    68
#define IDS_UNPACKING                   69
#define IDS_RETRIEVING                  69
#define IDS_UNPACKINGPERCENT            70
#define IDS_CONNECTING                  70
#define IDS_DOWNLOADING                 71
#define IDS_GETTARGET                   72
#define IDS_GET                         73
#define IDS_LOOK                        74
#define IDS_DROP                        75
#define IDS_PUT1                        76
#define IDS_PUT2                        77
#define IDS_USE                         78
#define IDS_UNUSE                       79
#define IDS_ATTACK                      80
#define IDS_OFFERTO                     81
#define IDS_OFFERITEMS                  82
#define IDS_APPLY                       83
#define IDS_ACTIVATE                    84
#define IDS_HTTPKEY                     85
#define IDS_HELPFILE                    86
#define IDS_BADCOMMAND                  87
#define IDS_DECOMPRESSING               90
#define IDS_APPNAME                     91
#define IDS_INIFILE                     92
#define IDS_YES                         93
#define IDS_NO                          94
#define IDS_BUYFROM                     95
#define IDS_CANTUPDATE                  97
#define IDS_NEEDNEWVERSION              98
#define IDS_CANTMOVE                    99
#define IDS_LONGCMDLINE                 100
#define IDI_ICON                        101
#define IDR_MAINMENU                    102
#define IDD_PORTDLG                     103
#define IDS_CANTMAKEDIR                 103
#define IDC_ADMIN1                      103
#define IDD_FTPERROR                    103
#define IDC_ADMIN2                      104
#define IDB_BACKGROUND                  105
#define IDS_NORSCS                      105
#define IDD_ITEMLISTSINGLE              106
#define IDS_CANTDELETE                  106
#define IDD_SAY                         107
#define IDS_CANTUNPACK                  107
#define IDD_ITEMLISTMULTIPLE            108
#define IDS_TOOFEWCOLORS                108
#define IDS_BADLENGTH                   109
#define IDD_DESC                        110
#define IDS_NOCHARACTERS                110
#define IDS_TRANSMITERROR               111
#define IDS_CANTUNCOMPRESS              112
#define IDS_BADTEMPFILE                 113
#define IDS_BADPERMISSION               114
#define IDS_BADMEM                      115
#define IDD_COMM                        116
#define IDS_BADARCHIVE                  116
#define IDD_SETTINGS                    116
#define IDD_COLOR                       117
#define IDS_DISKFULL                    117
#define IDD_OFFERSEND                   118
#define IDS_BADARCHIVE2                 118
#define IDD_LOGIN                       119
#define IDS_MISSINGARCHIVE              119
#define IDD_ABOUT                       120
#define IDS_UNKNOWNERROR                120
#define IDD_MAINMENU                    121
#define IDS_GUEST                       121
#define IDD_DOWNLOAD                    122
#define IDS_GUESTFULL                   122
#define IDD_PASSWORD                    123
#define IDC_TARGETCURSOR                125
#define IDD_TIMEOUT                     126
#define IDD_REGISTER                    127
#define IDD_ADMINNOTE                   128
#define IDS_NOSELLERS                   128
#define IDS_NOOFFERERS                  129
#define IDS_NOBROWSER                   130
#define IDI_CLOCK                       134
#define IDS_CANTFINDFILE                134
#define IDI_FORM                        135
#define IDS_FTPFAILED                   135
#define IDS_MISSINGFILE                 136
#define IDB_INTRO                       137
#define IDS_DEARCHIVEERROR              139
#define IDS_CANTINIT                    141
#define IDS_NOCONNECTION                142
#define IDS_BADCALLBACK                 143
#define IDS_CANTOPENFTPFILE             144
#define IDS_CANTWRITELOCALFILE          145
#define IDI_PHONE                       146
#define IDS_CANTREADFTPFILE             146
#define IDI_OFFER                       147
#define IDS_LATENCY0                    147
#define IDD_MSGBOX                      148
#define IDS_LATENCY1                    148
#define IDS_LATENCY2                    149
#define IDS_LATENCY3                    150
#define IDS_LATENCY4                    151
#define IDS_LATENCY5                    152
#define IDS_LATENCY6                    153
#define IDC_DROPCURSOR                  154
#define IDS_LATENCY7                    154
#define IDC_GETCURSOR                   155
#define IDD_WHO                         155
#define IDS_LATENCY8                    155
#define IDC_CROSSCURSOR                 156
#define IDC_INSIDECURSOR                157
#define IDS_LATENCYMETRIC               157
#define IDD_SERVERNUM                   158
#define IDD_ANNOTATE                    159
#define IDS_LAGBOXSUBNAME               159
#define IDB_ANNOTATE                    160
#define IDS_LAGBOXURL                   160
#define IDB_MAPBKGND                    161
#define IDS_LAGBOXDESC                  161
#define IDB_ABOUT                       162
#define IDS_PROFANITYREMOVED            162
#define IDB_IMAGELIST                   163
#define IDS_PROFANITYWARNING            163
#define IDB_BLUEWHO                     164
#define IDS_HOMEPAGEURL                 164
#define IDD_GUEST                       166
#define IDA_DOWNLOAD                    170
#define IDB_VIEWTREAT_TOPLEFT           171
#define IDB_VIEWTREAT_TOPRIGHT          172
#define IDB_VIEWTREAT_BOTTOMLEFT        173
#define IDB_VIEWTREAT_BOTTOMRIGHT       174
#define IDB_VIEWTREAT_TOPLEFT_HILIGHT   175
#define IDB_VIEWTREAT_TOPRIGHT_HILIGHT  176
#define IDB_VIEWTREAT_BOTTOMLEFT_HILIGHT 177
#define IDB_VIEWTREAT_BOTTOMRIGHT_HILIGHT 178
#define IDS_TARGETNOTVISIBLEFORATTACK   179
#define IDS_DEPOSIT_ITEMS               180
#define IDD_ASKDOWNLOAD                 181
#define IDS_SERVICE_SUCCESS             181
#define IDD_CUSTOMER_SERVICE            182
#define IDS_SERVICE_FAILURE             182
#define ID_OPTIONS_LOGOUTTIMER          184
#define ID_OPTIONS_LOGOUTTIMER185       185
#define ID_CONFIGMENU                   186
#define IDS_CANTSENDREQUEST             187
#define IDS_CANTGETFILESIZE             188
#define IDS_CANTSIGNUP                  189
#define IDD_SIGNUP                      189
#define IDS_TROUBLESHOOT                190
#define IDS_SIGNUPFAILED                191
#define IDS_USERNAMEINVALID             192
#define IDS_EMAILINVALID                193
#define IDS_EMAILINUSE                  194
#define IDS_PASSWORDINVALID             195
#define IDS_SERVERUNKNOWN               196
#define IDS_SIGNUPOFFLINE               197
#define IDS_SIGNUPUNKNOWNERROR          198
#define IDS_SIGNUPAPI                   199
#define IDS_WEBAPIDOMAIN                200
#define IDS_VERIFIEDAPI                 201
#define IDS_UNVERIFIED                  202
#define IDS_RESENDAPI                   203
#define IDS_SIGNUPMSG                   204
#define IDS_CANTATTACKSELF              205
#define IDC_PORTNUM                     1000
#define IDC_HOST                        1001
#define IDC_ITEMLIST                    1002
#define IDC_INSIDE                      1003
#define IDC_SAYBOX                      1004
#define IDC_FTPMESSAGE                  1004
#define IDC_ACTIVATE                    1004
#define IDC_MAINTEXT                    1005
#define IDC_ALL                         1008
#define IDC_DIALBUTTON                  1009
#define IDC_DESCBOX                     1010
#define IDC_DESCNAME                    1011
#define IDC_DESCBITMAP                  1012
#define IDC_DESCFIXED                   1013
#define IDD_OFFERRECEIVE                1014
#define IDD_YELL                        1015
#define IDC_NEXTMSG                     1016
#define IDD_AMOUNT                      1016
#define IDD_BUY                         1017
#define IDC_DELETEMSG                   1018
#define IDD_UPLOAD                      1018
#define IDD_ITEMLISTSORTED              1018
#define IDD_ITEMLISTSIMPLE              1019
#define IDD_DESCPLAYER                  1019
#define IDC_MAIN                        1020
#define IDD_DOWNLOADAD                  1020
#define IDC_BAUD9600                    1023
#define IDC_BAUD19200                   1024
#define IDC_BAUD2400                    1025
#define IDC_PARITYNONE                  1026
#define IDC_PARITYEVEN                  1027
#define IDC_PARITYODD                   1028
#define IDC_INITSTR                     1033
#define IDC_BAUD38400                   1034
#define IDC_NUMBER                      1035
#define IDC_COM1                        1036
#define IDC_COM2                        1037
#define IDC_COM3                        1038
#define IDC_COM4                        1039
#define IDC_ITEMFIND                    1042
#define IDC_TOOLBUTTON                  1043
#define IDC_FOREGROUND                  1044
#define IDC_BACKGROUND                  1045
#define IDC_TEXTINPUT                   1046
#define IDC_SAMPLETEXT                  1047
#define IDC_OFFERSEND                   1049
#define IDC_OFFERRECEIVE                1050
#define IDC_OFFEREDIT                   1051
#define IDC_SETITEMS                    1054
#define IDC_MESSAGE                     1055
#define IDC_LOOKLABEL                   1056
#define IDC_SAYLIST                     1057
#define IDC_BUTTONGAME                  1058
#define IDC_BUTTONROOM                  1059
#define IDC_BUTTONGROUP                 1060
#define IDC_MESSAGENUM                  1063
#define IDC_AMOUNTBOX                   1068
#define IDC_FRAME                       1072
#define IDC_COSTLIST                    1073
#define IDC_COST                        1074
#define IDC_SELLER                      1075
#define IDC_USERNAME                    1076
#define IDC_QUANLIST                    1076
#define IDC_PASSWORD                    1077
#define IDC_HANGUP                      1079
#define IDC_OK                          1080
#define IDC_MAINLIST                    1081
#define IDC_GUEST                       1081
#define IDC_SIGNUP                      1082
#define IDC_CREDITS                     1083
#define IDC_SCREENSIZE                  1085
#define IDC_FILESIZE                    1087
#define IDC_BYTES                       1088
#define IDC_PERCENT                     1089
#define IDC_SPEED                       1090
#define IDC_ERRORS                      1092
#define IDC_COMMENT                     1093
#define IDC_FILENAME                    1095
#define IDC_OLDPASSWD                   1096
#define IDC_NEWPASSWD1                  1097
#define IDC_NEWPASSWD2                  1098
#define IDC_TIMEOUTENABLE               1099
#define IDC_TIMEOUTMINUTES              1100
#define IDC_NAME                        1101
#define IDC_ADDRESS1                    1102
#define IDC_ADDRESS2                    1103
#define IDC_ADDRESS3                    1104
#define IDC_PHONE                       1105
#define IDC_NOTEEDIT                    1106
#define IDC_CHARLIST                    1107
#define IDC_RESET                       1109
#define IDC_CHARNAME                    1111
#define IDC_TERMINALMODE                1112
#define IDC_ATTEMPTS                    1114
#define IDC_LIST1                       1115
#define IDC_USERLIST                    1115
#define IDC_SUBJECT                     1117
#define IDC_TIMEOUT                     1117
#define IDC_EDIT                        1117
#define IDC_SERVERNAME                  1119
#define IDC_GROUPNAME                   1121
#define IDC_REDIAL                      1122
#define IDC_TEXT                        1128
#define IDC_MSGBOXICON                  1129
#define IDC_NETWORK                     1130
#define IDC_GRAPH                       1133
#define IDC_AUTOCONNECT                 1134
#define IDC_TOOLTIP                     1135
#define IDC_FILEGRAPH                   1136
#define IDC_UNUSE                       1137
#define IDC_DROP                        1138
#define IDC_USE                         1139
#define IDC_GET                         1140
#define IDC_BROADCAST                   1140
#define IDC_IGNOREALL                   1141
#define IDC_APPLY                       1141
#define IDC_DRAWNAMES                   1143
#define IDC_SCROLLLOCK                  1145
#define IDC_PAIN                        1146
#define IDC_TOOLTIPS                    1147
#define IDC_INVNUM                      1148
#define IDC_SERVERNUM                   1150
#define IDC_MUSIC                       1150
#define IDC_SOUNDFX                     1151
#define IDC_NUMPLAYERS                  1152
#define IDC_LOOPSOUNDS                  1152
#define IDC_SAFETY                      1153
#define IDC_GUILD                       1154
#define IDC_RANDSOUNDS                  1154
#define IDC_BROWSER                     1155
#define IDC_AGE                         1155
#define IDC_URL                         1156
#define IDC_URLBUTTON                   1157
#define IDC_URLLABEL                    1158
#define IDC_ADMIN                       1159
#define IDC_ANNOTATE                    1160
#define IDC_DELETE                      1161
#define IDC_FIND                        1162
#define IDC_BOUNCE                      1163
#define IDC_AGELABEL                    1164
#define IDC_PROFANESETTINGS             1164
#define IDC_TOOLBAR                     1165
#define IDD_WITHDRAWAL                  1165
#define ID_DESCNAME                     1166
#define IDC_SCROLL                      1167
#define IDC_SPECIAL1                    1168
#define IDC_SPECIAL2                    1169
#define IDC_GUESTBAR                    1170
#define IDC_ANIMATE1                    1171
#define IDC_AGELABEL2                   1172
#define IDC_PROFANE                     1173
#define IDC_RADIO1                      1174
#define IDC_RADIO2                      1175
#define IDC_EDIT1                       1176
#define IDC_BUTTON1                     1177
#define IDC_BUTTON2                     1178
#define IDC_CHECK1                      1179
#define IDC_TARGETHALO1                 1180
#define IDC_TARGETHALO2                 1181
#define IDC_SPIN1                       1181
#define IDC_TARGETHALO3                 1182
#define IDC_NEXT                        1182
#define IDC_PREV                        1183
#define IDC_SPARKS                      1184
#define IDC_BTN_DEMO                    1189
#define IDC_ASK_DOWNLOAD_REASON         1191
#define IDC_UPDATE                      1192
#define IDC_SIZE_UPDATE                 1193
#define IDC_TIME_UPDATE_566             1194
#define IDC_TIME_UPDATE_288             1195
#define IDC_NEW_TO_MERIDIAN_59          1196
#define IDC_VALE                        1197
#define IDC_REVELATIONS                 1198
#define IDC_DRAWMAP                     1198
#define IDC_ORIGINAL                    1199
#define IDC_COLORCODES                  1199
#define IDC_STATIC1                     1199
#define IDC_CAPTION                     1200
#define IDC_RICHEDIT1                   1201
#define IDC_MAP_ANNOTATIONS             1202
#define IDC_SOUND_VOLUME                1205
#define IDC_MUSIC_VOLUME                1206
#define IDC_SERVER_101                  1206
#define IDC_SOUND_VOLUME2               1207
#define IDC_SERVER_102                  1207
#define ID_SU_EMAIL                     1208
#define ID_SU_USERNAME                  1209
#define ID_SU_PW1                       1210
#define ID_SU_PW2                       1211
#define ID_SU_SERVER                    1212
#define IDC_SIGNUP_OK                   1213
#define IDC_NEW_EMAIL                   1214
#define IDC_NEW_USERNAME                1215
#define IDC_NEW_PW1                     1216
#define IDC_NEW_PW2                     1217
#define IDC_EMAIL_ADDRESS               1218
#define IDC_SIGNUP_TROUBLESHOOT         1219
#define ID_SPINNING_CUBE                1220
#define ID_GAME_EXIT                    3002
#define ID_FONT_MAIL                    3014
#define ID_FONT_LIST                    3015
#define ID_FONT_GAMETEXT                3016
#define ID_FONT_TITLES                  3017
#define ID_FONT_STATISTICS              3019
#define ID_FONT_MAINBUTTONS             3020
#define ID_OPTIONS_SAVEEXIT             3021
#define ID_COLOR_MAIN                   3024
#define ID_COLOR_DEFAULTS               3025
#define ID_FONT_DEFAULTS                3026
#define ID_COLOR_LISTSEL                3027
#define ID_COLOR_MAIL                   3028
#define ID_OPTIONS_SAVENOW              3029
#define ID_COLOR_HIGHLIGHT              3030
#define ID_COLOR_TEXT                   3032
#define ID_OPTIONS_SOUND                3033
#define ID_OPTIONS_MUSIC                3034
#define ID_COLOR_DIALOG                 3035
#define ID_HELP_CONTENTS                3036
#define ID_HELP_ABOUT                   3037
#define ID_FONT_MENU                    3038
#define ID_COLOR_EDIT                   3039
#define ID_COLOR_LIST                   3042
#define ID_FONT_INPUT                   3043
#define ID_FONT_RMTITLE                 3044
#define ID_COLOR_ROOMTITLE              3045
#define ID_COLOR_STATS                  3047
#define ID_FONT_INVENTORY               3049
#define ID_FONT_LABELS                  3049
#define ID_COLOR_INVENTORY              3050
#define ID_COLOR_INVNUM                 3050
#define ID_COLOR_INVENTORYSEL           3051
#define ID_OPTIONS_TIMEOUT              3052
#define ID_OPTIONS_AREA                 3057
#define ID_GAME_SETTINGS                3060
#define ID_GAME_CONNECT                 3061
#define ID_GAME_DISCONNECT              3062
#define ID_OPTIONS_ANIMATION            3064
#define ID_COLOR_BAR1                   3500
#define ID_COLOR_BAR2                   3501
#define ID_COLOR_BAR3                   3502
#define ID_OPTIONS_DRAWNAMES            3503
#define ID_COLOR_SYSMSG                 3504
#define ID_COLOR_BAR4                   3505
#define ID_GAME_PASSWORD                3506
#define ID_GAME_PRINTMAP                3507
#define ID_OPTIONS_FONT_MAP_TITLE       3508
#define ID_OPTIONS_FONT_MAP_LABEL       3509
#define ID_OPTIONS_FONT_MAP_TEXT        3510
#define ID_HELP_REQUEST_CS              3511
#define IDM_DRAW_MAP                    3512

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         3513
#define _APS_NEXT_CONTROL_VALUE         1221
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
