#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\spell.bof
BOFS = heal.bof atakspel.bof rescue.bof earthqua.bof \
       dmspell.bof mend.bof winds.bof \
       remcurse.bof blink.bof \
       cdisease.bof cpoison.bof discord.bof hospice.bof \
       majheal.bof dishonor.bof \
       blind.bof hold.bof defile.bof radiusench.bof \
       creaweap.bof enfeeble.bof shatter.bof swap.bof \
       brittle.bof creafood.bof dement.bof enchwp.bof fade.bof focus.bof \
       holywp.bof manabomb.bof unholywp.bof \
       purify.bof nodebrst.bof \
       illform.bof identify.bof reveal.bof shroud.bof engrave.bof \
       cursewp.bof anon.bof boon.bof jala.bof \
       dispillu.bof summrefl.bof apparitn.bof creasphm.bof forget.bof \
       seduce.bof morph.bof portlife.bof artifice.bof \
       forsight.bof bait.bof persench.bof vertigo.bof \
       roomench.bof flash.bof animate.bof \
       holysymb.bof finlrite.bof fdeath.bof multicst.bof \
       summtwin.bof brthlife.bof glow.bof seance.bof \
       sweep.bof mysttch.bof relay.bof distill.bof \
       dazzle.bof purge.bof elusion.bof walspell.bof deathrift.bof \
	   creabsax.bof utility.bof crysmana.bof

!include $(KODDIR)\kod.mak
