#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\spell.bof
BOFS = heal.bof atakspel.bof rescue.bof \
       dmspell.bof winds.bof remcurse.bof blink.bof \
       cdisease.bof cpoison.bof discord.bof hospice.bof \
       majheal.bof dishonor.bof \
       blind.bof hold.bof defile.bof radiusench.bof \
       creaweap.bof enfeeble.bof shatter.bof swap.bof \
       brittle.bof creafood.bof dement.bof fade.bof focus.bof \
       manabomb.bof purify.bof nodebrst.bof \
       illform.bof engrave.bof cursewp.bof anon.bof boon.bof \
       dispillu.bof summrefl.bof apparitn.bof creasphm.bof forget.bof \
       seduce.bof morph.bof portlife.bof \
       forsight.bof bait.bof persench.bof vertigo.bof \
       roomench.bof flash.bof animate.bof \
       holysymb.bof finlrite.bof fdeath.bof multicst.bof \
       summtwin.bof brthlife.bof seance.bof \
       sweep.bof mysttch.bof relay.bof distill.bof \
       dazzle.bof purge.bof elusion.bof walspell.bof deathrift.bof \
       utility.bof crysmana.bof itemench.bof

!include $(KODDIR)\kod.mak
