#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\thrusting.bof
BOFS = goldswrd.bof longswrd.bof mystswrd.bof neruswd.bof \
        	riijaswd.bof shrtswrd.bof

!include $(KODDIR)\kod.mak
