TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = $(TOPDIR)\resource\graphics

.SUFFIXES: .bbg

BGFS = chupa.bgf chupaX.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	$(RM) $(CLIENTRUNDIR)\resource\chupa.bgf
	$(RM) $(CLIENTRUNDIR)\resource\chupaX.bgf

clean-frames:
	$(RM) *.bmp
