#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\troop.bof
BOFS  = duketr.bof printr.bof rebeltr.bof necrotr.bof factionmage.bof


!include $(KODDIR)\kod.mak
