#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\roomench.bof
BOFS = shalbane.bof qorbane.bof martyrs.bof \
       antimag.bof darkness.bof dethlink.bof \
       heat.bof killing.bof light.bof sandstor.bof \
       truce.bof winds.bof silence.bof forceslt.bof

!include $(KODDIR)\kod.mak
