#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\touchatk.bof
BOFS = flametch.bof holytch.bof icyfing.bof zap.bof acidtch.bof unholytch.bof

!include  $(KODDIR)\kod.mak
