#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\tostwn.bof
BOFS  = TsUrchin.bof TsApoth.bof TsSmith.bof TsInnK.bof TsBanker.bof \
        tswatch.bof dkgrd.bof basicinn.bof

!include $(KODDIR)\kod.mak
