#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\tostwn.bof
BOFS  = tsurchin.bof tsapoth.bof tssmith.bof tsinnk.bof tsbanker.bof \
        tswatch.bof dkgrd.bof basicinn.bof

!include $(KODDIR)\kod.mak
