# Makefile for admin DLL

TOPDIR=..\..
!include $(TOPDIR)\common.mak

MODULE = admin

!include $(MODULEDIR)\module.mak

$(OUTDIR)\admin.dll: \
    $(OUTDIR)\admin.obj \
    $(OUTDIR)\admindlg.obj \
    $(OUTDIR)\adminprs.obj \
    $(OUTDIR)\admin.res 


!include $(TOPDIR)\rules.mak
