#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\boon.bof
BOFS = agilboon.bof aimboon.bof hpboon.bof intboon.bof manaboon.bof mystboon.bof \
	stamboon.bof strboon.bof vigboon.bof


!include $(KODDIR)\kod.mak
