#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\kocarm.bof

BOFS =  kocatan.bof kocsouth.bof \
	kocapoth.bof koctav.bof kocinn.bof kocbank.bof kocstore.bof \
	koctail.bof kocblack.bof kochoh.bof kochoha.bof kochohb.bof \
	koctower.bof

!include $(KODDIR)\kod.mak

