#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\passitem.bof
BOFS = attmod.bof defmod.bof healer.bof key.bof \
	numbitem.bof scepter.bof weapon.bof chalice.bof \
	spdregg.bof spdreggX.bof \
	arsenic.bof necklace.bof ring.bof pforget.bof token.bof \
	minigame.bof gift.bof pillufrm.bof instrum.bof sanctkey.bof \
	totem.bof rose.bof orechunk.bof offering.bof letter.bof \
	nerudore.bof swshard.bof bosshead.bof inscript.bof formula.bof \
	avarfeth.bof chiksoup.bof recipe.bof sachaqua.bof \
	junk.bof dresspat.bof scamscrl.bof shruhead.bof cncllttr.bof lovelttr.bof \
	prism.bof orecheap.bof neclettr.bof taxlettr.bof ncwrnlet.bof potaphro.bof \
	warlettr.bof factflag.bof bardnote.bof mystpot.bof mystwand.bof lablpot.bof \
	lablwand.bof roomkeyc.bof hstone.bof spelitem.bof rod.bof warjoin.bof \
	betap.bof specgift.bof manacrys.bof spcgift2.bof karmapotion.bof gem.bof reagentbag.bof

!include $(KODDIR)\kod.mak
