#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\passitem.bof
BOFS = arsenic.bof attmod.bof betap.bof bosshead.bof \
   chalice.bof defmod.bof factflag.bof gem.bof gift.bof healer.bof \
   hstone.bof inscript.bof instrum.bof junk.bof karmapotion.bof key.bof \
   manacrys.bof minigame.bof necklace.bof nerudore.bof numbitem.bof \
   offering.bof orecheap.bof orechunk.bof pforget.bof pillufrm.bof \
   prism.bof questitem.bof reagentbag.bof ring.bof rod.bof roomkeyc.bof \
   rose.bof sanctkey.bof scepter.bof shruhead.bof spcgift2.bof spdregg.bof \
   spdreggX.bof specgift.bof spelitem.bof spelitemsplit.bof swshard.bof \
   token.bof totem.bof warjoin.bof weapon.bof bardnote.bof qormasgift.bof \
   easteregg.bof lorebook.bof

!include $(KODDIR)\kod.mak
