# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = ratking.bgf ratkingX.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\ratking.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\ratkingX.bgf 2>nul
