#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\persench.bof
BOFS = haste.bof detinvis.bof detgood.bof denial.bof detevil.bof respois.bof cloak.bof freeact.bof\
       eavesdrp.bof eagleyes.bof bless.bof gort.bof mshield.bof nightv.bof shadform.bof\
       strength.bof resist.bof invis.bof deflect.bof touchatk.bof gaze.bof karahol.bof\
       dethlink.bof

!include $(KODDIR)\kod.mak
