#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\persench.bof
BOFS = anon.bof \
       bless.bof \
       cloak.bof \
       deflect.bof \
       denial.bof \
       detevil.bof \
       detgood.bof \
       dethlink.bof \
       detinvis.bof \
       eagleyes.bof \
       eavesdrp.bof \
       focus.bof \
       freeact.bof \
       gaze.bof \
       gort.bof \
       haste.bof \
       invis.bof \
       karahol.bof \
       mshield.bof \
       nightv.bof \
       resist.bof \
       respois.bof \
       shadform.bof \
       strength.bof \
       touchatk.bof

!include $(KODDIR)\kod.mak
