#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\ghall.bof

BOFS = guildh1.bof guildh2.bof guildh3.bof guildh4.bof guildh5.bof guildh6.bof \
        guildh7.bof guildh8.bof guildh9.bof guildh10.bof guildh11.bof guildh12.bof \
        guildh13.bof guildh14.bof guildh15.bof

!include $(KODDIR)\kod.mak

