#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\trestype.bof
BOFS = wimptres.bof notres.bof spquent.bof med-tght.bof wmp-medt.bof \
   tought.bof mediumt.bof ghostt.bof verytght.bof orctres.bof \
   fairytrs.bof entt.bof mummytrs.bof \
   lowhumt.bof medhumt.bof highhumt.bof rattres.bof zombiet.bof \
   caveorct.bof orcwizt.bof orcpitt.bof avart.bof avarsht.bof \
   avarcht.bof lupkingt.bof dflyt.bof licht.bof \
   dethspdt.bof skel2t.bof skel3t.bof skel4t.bof narthylt.bof \
   wrmlarvt.bof wrmquent.bof dangelt.bof newbietrs.bof thrasht.bof \
   statuet.bof kriipat.bof molluskt.bof shadowbeastt.bof ratktres.bof \
   earthelet.bof fireelet.bof iceelet.bof neruelet.bof easterbunnyt.bof \
   killerbunnyt.bof xeoairt.bof xeoeartht.bof xeofiret.bof xeowatert.bof \
   xeoacidt.bof xeounholyt.bof xeoholyt.bof xeonerut.bof xeoillt.bof

!include $(KODDIR)\kod.mak
