#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\kocatwn.bof
BOFS  = kcapoth.bof kcbart.bof kcinnk.bof kcsentry.bof kcbanker.bof \
        kcvaultm.bof kcmerch.bof kctailor.bof kclangua.bof kcsmith.bof \
        kcguardE.bof kcguardG.bof kcweapon.bof kcshopk.bof kcbonepr.bof \
        kcmadsci.bof kcbowmak.bof
       

!include $(KODDIR)\kod.mak
