#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\debuff.bof
BOFS = blind.bof dazzle.bof dement.bof dishonor.bof enfeeble.bof\
       forget.bof hold.bof seduce.bof vertigo.bof

!include $(KODDIR)\kod.mak
