#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\debuff.bof
BOFS = blind.bof \
       dazzle.bof \
       disease.bof \
       dishonor.bof \
       forget.bof \
       hold.bof \
       seduce.bof \
       vertigo.bof

!include $(KODDIR)\kod.mak
