#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\wanderer.bof
BOFS  =  jGeneral.bof minstrel.bof heretic.bof dkwizard.bof huntghst.bof izzio.bof

!include $(KODDIR)\kod.mak
