#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\food.bof
BOFS = inkycap.bof snack.bof watrskin.bof meatpie.bof apple.bof \
       bread.bof mug.bof spideye.bof drumstik.bof pork.bof \
       grapes.bof ftncooky.bof soup.bof goblet.bof gobletst.bof stew.bof \
       gobletwn.bof kocmug.bof cheese.bof mint.bof turkyleg.bof chaosfood.bof \
       cookie.bof pear.bof orange.bof

!include $(KODDIR)\kod.mak
