#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\food.bof
BOFS = goodfood.bof mediumfood.bof lowfood.bof statfood.bof heartyfood.bof \
       mint.bof chaosfood.bof

!include $(KODDIR)\kod.mak
