#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jala.bof
BOFS = jig.bof hinder.bof restorat.bof invigor.bof rejuven.bof warptime.bof \
       manaconv.bof melcholy.bof mirth.bof

!include $(KODDIR)\kod.mak
