#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\barlqtwn.bof
BOFS  = bqurchin.bof bqmerch.bof bqbart.bof bqinnk.bof bqapoth.bof bqbanker.bof \
        gcreator.bof assassin.bof bqclerk.bof bqsmith.bof bqtailor.bof bqvaultm.bof \
        pringrd.bof

!include $(KODDIR)\kod.mak
