#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\radiusench.bof
BOFS = umbrella.bof killing.bof antimag.bof truce.bof winds.bof sandstor.bof \
       mirth.bof melcholy.bof

!include $(KODDIR)\kod.mak
