#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\questtemplate.bof
BOFS = shaldiscqt.bof krandiscqt.bof farendiscqt.bof qordiscqt.bof \
       fadepupilqt.bof dementpupilqt.bof scimprofqt.bof sporepupilqt.bof \
       princessqt.bof dukeloyaltyqt.bof rebelloyaltyqt.bof dukejoinqt.bof \
       rebeljoinqt.bof soldierqt.bof guildshieldqt.bof guildshintroqt.bof \
       luteqt.bof truthspellqt.bof truthendbranchqt.bof bonepriestessqt.bof \
       madscidflyqt.bof tradingpostqt.bof bowmakerqt.bof chickensoupqt.bof \
       stunteddwarfqt.bof hypochondriacqt.bof offeringqt.bof seraphymqt.bof \
       priestessinsigniaqt.bof monkinsigniaqt.bof factioninsigniaqt.bof \
       mysterymobqt.bof moxalscamoneqt.bof moxalscamtwoqt.bof
      

!include $(KODDIR)\kod.mak
