#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\offeringqt.bof
BOFS = qorofferingqt.bof shalofferingqt.bof farenofferingqt.bof \
       kranofferingqt.bof riijaofferingqt.bof

!include $(KODDIR)\kod.mak
