#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weapatt.bof
BOFS = waspellt.bof waghall.bof wafactn.bof wacerem.bof wapunish.bof \
       waexpert.bof wacursed.bof waench.bof wabonker.bof wablindr.bof \
       waparal.bof wavamper.bof watwist.bof waspell.bof waglow.bof \
       wapurge.bof wamanasiphon.bof

!include $(KODDIR)\kod.mak
