#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\util.bof
BOFS = system.bof library.bof parlia.bof assgame.bof questengine.bof lore.bof \
       aarchive.bof necbal.bof nodeattk.bof rntmaint.bof factgame.bof eventtxt.bof \
       warevent.bof statistics.bof settings.bof chaosnight.bof qormas.bof \
       survivalmaint.bof gameevent.bof gameeventengine.bof oogtime.bof

!include $(KODDIR)\kod.mak
