#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\kcforest.bof

BOFS = ka0.bof ka1.bof ka2.bof ka3.bof ka4.bof ka5.bof kb1.bof kb2.bof kb3.bof \
       kb4.bof kb5.bof kc1.bof kc2.bof kc3.bof kc4.bof kc5.bof kd1.bof \
       kd2.bof kd3.bof kd4.bof ke2.bof ke4.bof  kmadscih.bof



!include $(KODDIR)\kod.mak

