#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\guildcmd.bof
BOFS =  gcabdic.bof gcally.bof gcenemy.bof gcexile.bof \
     gcinvite.bof gcnoally.bof gcnoenem.bof gcrennce.bof gcpword.bof\
          gcroster.bof gcvote.bof gcsetrnk.bof gcdisbnd.bof gcaband.bof

!include $(KODDIR)\kod.mak
