#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jasprtwn.bof
BOFS  = jsbanker.bof jsmerch.bof jselder.bof jssmith.bof jsbart.bof jsinnk.bof jasvaultm.bof
BOFS2 = jsurchin.bof

!include $(KODDIR)\kod.mak
