# Makefile for downloadable client DLLs

TOPDIR=..\..
!include $(TOPDIR)\common.mak

MODULE = merintr

!include $(MODULEDIR)\module.mak

$(OUTDIR)\merintr.dll: \
      $(OUTDIR)\merintr.obj \
      $(OUTDIR)\mermain.obj \
      $(OUTDIR)\spells.obj \
      $(OUTDIR)\command.obj \
      $(OUTDIR)\groups.obj \
      $(OUTDIR)\userarea.obj \
      $(OUTDIR)\alias.obj \
      $(OUTDIR)\enchant.obj \
      $(OUTDIR)\inventry.obj \
      $(OUTDIR)\stats.obj \
      $(OUTDIR)\statlist.obj \
      $(OUTDIR)\statcach.obj \
      $(OUTDIR)\statbtn.obj \
      $(OUTDIR)\statmain.obj \
      $(OUTDIR)\statnum.obj \
      $(OUTDIR)\guild.obj \
      $(OUTDIR)\guildinv.obj \
      $(OUTDIR)\guildhal.obj \
      $(OUTDIR)\guildbuy.obj \
      $(OUTDIR)\guildshi.obj \
      $(OUTDIR)\guildaly.obj \
      $(OUTDIR)\guildmem.obj \
      $(OUTDIR)\guildmtr.obj \
      $(OUTDIR)\actions.obj \
      $(OUTDIR)\drawint.obj \
      $(OUTDIR)\groupdlg.obj \
      $(OUTDIR)\skills.obj \
      $(OUTDIR)\language.obj \
      $(OUTDIR)\merintr.res

!include $(TOPDIR)\rules.mak
