// Meridian 59, Copyright 1994-2012 Andrew Kirmse and Chris Kirmse.
// All rights reserved.
//
// This software is distributed under a license that is described in
// the LICENSE file that accompanies it.
//
// Meridian is a registered trademark.
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by merintr.rc
//
#define IDS_CAST                        1
#define IDS_SPELLS                      2
#define IDS_TBDROP                      3
#define IDS_TBGET                       4
#define IDS_TBSAY                       5
#define IDS_TBCAST                      6
#define IDS_TBMAP                       7
#define IDS_TBHELP                      8
#define IDS_TBREST                      9
#define IDS_TBSTAND                     10
#define IDS_HEALTH                      11
#define IDS_MANA                        12
#define IDS_VIGOR                       13
#define IDS_TBSMILE                     14
#define IDS_TBFROWN                     15
#define IDS_NOTELLNAME                  16
#define IDS_DUPLICATETELLNAME           17
#define IDS_DUPLICATEGROUPNAME          18
#define IDS_TOOMANYGROUPS               19
#define IDS_GROUPFULL                   20
#define IDS_GROUPNOTON                  21
#define IDS_BADGROUPNAME                22
#define IDS_ALREADYGROUP                23
#define IDS_DUPLICATESPELLNAME          24
#define IDS_NOSPELLNAME                 25
#define IDS_SUICIDE                     26
#define IDS_NOWITHDRAWAMOUNT            27
#define IDS_NODEPOSITAMOUNT             28
#define IDS_GROUPFULLDLG                29
#define IDS_CANTADDNAMEDLG              30
#define IDS_GROUPFAILEDDLG              31
#define IDS_GROUPADDED                  32
#define IDS_GROUPMEMBERS                33
#define IDS_NOGROUPS                    34
#define IDS_GROUPLIST                   35
#define IDS_GROUPDELETED                36
#define IDS_NAMESDELETED                37
#define IDS_GROUPCREATED                38
#define IDS_REST                        39
#define IDS_STAND                       40
#define IDS_RESTING                     41
#define IDS_STANDING                    42
#define IDS_SPELLRESTING                43
#define IDS_SPELLPARALYZED              44
#define IDS_SUICID                      45
#define IDS_GUILDBLANK                  46
#define IDS_WINDOWTITLE                 47
#define IDS_RENOUNCE                    48
#define IDS_ABDICATE                    49
#define IDS_MRANK1                      50
#define IDS_MRANK2                      51
#define IDS_MRANK3                      52
#define IDS_MRANK4                      53
#define IDS_MRANK5                      54
#define IDS_FRANK1                      55
#define IDS_FRANK2                      56
#define IDS_FRANK3                      57
#define IDS_FRANK4                      58
#define IDS_FRANK5                      59
#define IDS_GUILDUNALIGNED              60
#define IDS_DISBAND                     61
#define IDS_GUILDALLY                   62
#define IDS_GUILDENEMY                  63
#define IDS_ABANDON                     64
#define IDS_GUILDCONFIGTITLE            65
#define IDS_INVITE                      66
#define IDS_GUILDMEMBERS                67
#define IDS_GUILDALLIES                 68
#define IDS_GUILDMASTER                 69
#define IDS_NOBODY                      70
#define IDS_DONE                        71
#define IDS_GHEADER1                    72
#define IDS_GHEADER2                    73
#define IDS_GHEADER3                    74
#define IDS_PASSWORDBLANK               75
#define IDS_GUILDSHIELD                 76
#define IDS_TT_STATS                    77
#define IDS_TT_SPELLS                   78
#define IDS_TT_SKILLS                   79
#define IDS_ACTIONS                     80
#define IDS_SGROUP1                     81
#define IDS_SGROUP2                     82
#define IDS_SGROUP3                     83
#define IDS_SGROUP5                     84
#define IDS_SGROUP4                     85
#define IDS_SGROUP6                     86
#define IDS_TT_INVENTORY                87
#define IDS_HEL                         88
#define IDS_MENU_WHO                    89
#define IDS_INVALIDALIAS                90
#define IDS_AMBIGUOUSALIAS              91
#define IDS_CMDALIASDEFINED             92
#define IDS_CMDALIASREMOVED             93
#define IDS_AHEADER0                    94
#define IDS_AHEADER1                    95
#define IDS_MENU_GROUP                  96
#define IDS_MENU_ALIAS                  97
#define IDS_TOUGHER                     98
#define IDS_TT_QUEST                    99
#define IDS_LANGUAGE_MENU               100
#define IDD_ALIAS                       102
#define IDD_STATS                       103
#define IDD_GUILDCONFIG                 104
#define IDD_GUILDCREATE                 105
#define IDD_GUILDINVITE                 106
#define IDD_GUILDHALLS                  107
#define IDB_ULTOP                       110
#define IDB_URTOP                       111
#define IDB_LLLEFT                      112
#define IDB_LRBOTTOM                    113
#define IDB_LLBOTTOM                    114
#define IDB_LRRIGHT                     115
#define IDB_ULLEFT                      116
#define IDB_URRIGHT                     117
#define IDB_TOP                         118
#define IDB_BOTTOM                      119
#define IDB_LEFT                        120
#define IDB_RIGHT                       121
#define IDB_IULTOP                      122
#define IDB_IURTOP                      123
#define IDB_ILLLEFT                     124
#define IDB_ILRBOTTOM                   125
#define IDB_ILLBOTTOM                   126
#define IDB_ILRRIGHT                    127
#define IDB_IULLEFT                     128
#define IDB_IURRIGHT                    129
#define IDB_ITOP                        130
#define IDB_IBOTTOM                     131
#define IDB_ILEFT                       132
#define IDB_IRIGHT                      133
#define IDB_SBUTTON1                    134
#define IDB_SBUTTON2                    135
#define IDB_SBUTTON3                    136
#define IDD_GROUP                       140
#define IDD_GUILDSHIELD                 143
#define IDB_SAY                         149
#define IDB_DROP                        150
#define IDB_GET                         151
#define IDB_MAP                         152
#define IDB_CAST                        153
#define IDB_HELP                        154
#define IDB_REST                        155
#define IDB_STAND                       156
#define IDD_INVENTORY                   157
#define IDB_INVINUSE                    158
#define IDB_INVCURSOR                   159
#define IDD_GUILDMEMBERS                159
#define IDB_SMILE                       160
#define IDD_GUILDALLIES                 160
#define IDB_FROWN                       161
#define IDD_GUILDMASTER                 161
#define IDB_INVBKGND                    162
#define IDB_STATSBKGND                  163
#define IDB_BARLEFT                     164
#define IDB_BARRIGHT                    165
#define IDB_BARTOP                      166
#define IDB_BARBOTTOM                   167
#define IDB_SULTOP                      168
#define IDB_SURTOP                      169
#define IDB_SLLLEFT                     170
#define IDB_SLRBOTTOM                   171
#define IDB_SLLBOTTOM                   172
#define IDB_SLRRIGHT                    173
#define IDB_SULLEFT                     174
#define IDB_SURRIGHT                    175
#define IDB_STOP                        176
#define IDB_SBOTTOM                     177
#define IDB_SLEFT                       178
#define IDB_SRIGHT                      179
#define IDD_CMDALIAS                    180
#define IDB_SBUTTON4                    181
#define IDD_SUICIDE                     181
#define IDB_EULTOP                      182
#define IDB_EULLEFT                     183
#define IDB_EURTOP                      184
#define IDB_EURRIGHT                    185
#define IDB_ELLBOTTOM                   186
#define IDB_ELLLEFT                     187
#define IDB_ELRBOTTOM                   188
#define IDB_ELRRIGHT                    189
#define IDB_EREPEAT                     190
#define IDS_TARGETNOTVISIBLEFORCAST     191
#define IDB_MULTOP                      192
#define IDB_MULLEFT                     193
#define IDB_MURTOP                      194
#define IDB_MURRIGHT                    195
#define IDB_MLLBOTTOM                   196
#define IDB_MLLLEFT                     197
#define IDB_MLRBOTTOM                   198
#define IDB_MLRRIGHT                    199
#define IDB_MUREPEAT                    200
#define IDB_MLREPEAT                    201
#define IDB_MRREPEAT                    202
#define IDB_MBREPEAT                    203
#define IDB_SBUTTON1_LEFT               204
#define IDB_SBUTTON2_LEFT               205
#define IDB_SBUTTON3_LEFT               206
#define IDB_SBUTTON4_LEFT               207
#define IDB_SBUTTON1_MID                208
#define IDB_SBUTTON2_MID                209
#define IDB_SBUTTON3_MID                210
#define IDB_SBUTTON4_MID                211
#define IDB_SBUTTON1_RIGHT              212
#define IDB_SBUTTON2_RIGHT              213
#define IDB_SBUTTON3_RIGHT              214
#define IDB_SBUTTON4_RIGHT              215
#define IDB_BULTOP                      216
#define IDB_BULLEFT                     217
#define IDB_BURTOP                      218
#define IDB_BURRIGHT                    219
#define IDB_BLLBOTTOM                   220
#define IDB_BLLLEFT                     221
#define IDB_BLRBOTTOM                   222
#define IDB_BLRRIGHT                    223
#define IDB_BUREPEAT                    224
#define IDB_BLREPEAT                    225
#define IDB_BRREPEAT                    226
#define IDB_BBREPEAT                    227
#define IDB_ELREPEAT                    229
#define IDB_ERREPEAT                    230
#define IDB_EUREPEAT                    231
#define IDB_EBREPEAT                    232
#define IDB_BITMAP1                     234
#define IDB_SELFTRGT                    234
#define IDS_MENU_CMDALIAS               235
#define IDS_MENU_GUILD                  236
#define IDS_MENU_WAVE                   237
#define IDS_MENU_POINT                  238
#define IDS_MENU_DANCE                  239
#define IDS_MENU_HAPPY                  240
#define IDS_MENU_SAD                    241
#define IDS_MENU_NEUTRAL                242
#define IDS_MENU_WRY                    243
#define IDB_SBUTTON5_LEFT               244
#define IDS_DOCAST                      245
#define IDC_ALIASF1                     1000
#define IDC_ALIASF2                     1001
#define IDC_DEFINE                      1001
#define IDC_INVITE                      1001
#define IDC_FACE                        1001
#define IDC_SHIELD                      1001
#define IDC_ALIASF3                     1002
#define IDC_REMOVE                      1002
#define IDC_ALIASF4                     1003
#define IDC_ALIASF5                     1004
#define IDC_ALIASF6                     1005
#define IDC_ALIASF7                     1006
#define IDC_INVENTORY                   1006
#define IDC_ALIASF8                     1007
#define IDC_ALIASF9                     1008
#define IDC_ALIASF10                    1009
#define IDC_ALIASF11                    1010
#define IDC_ALIASF12                    1011
#define IDC_PATTERN_1                   1016
#define IDC_PATTERN_PREV                1016
#define IDC_PATTERN_2                   1017
#define IDC_PATTERN_NEXT                1017
#define IDC_COLOR2_1                    1018
#define IDC_COLOR2_PREV                 1018
#define IDC_COLOR1_1                    1019
#define IDC_COLOR1_PREV                 1019
#define IDC_STATS                       1021
#define IDC_COLOR1_2                    1022
#define IDC_COLOR1_NEXT                 1022
#define IDC_COLOR2_2                    1024
#define IDC_COLOR2_NEXT                 1024
#define IDC_STATBUTTON                  1029
#define IDC_STATLIST                    1052
#define IDC_ROOMTITLE                   1066
#define IDC_INVSCROLL                   1084
#define IDC_ENCHANTMENT                 1199
#define IDC_CHECK_F1                    1199
#define IDC_CHECK_F2                    1200
#define IDC_CHECK_F3                    1201
#define IDC_GUILDLIST                   1201
#define IDC_CHECK_F4                    1202
#define IDC_INROOMLIST                  1202
#define IDC_CHECK_F5                    1203
#define IDC_VOTE                        1203
#define IDC_CHECK_F6                    1204
#define IDC_CHECK_F7                    1205
#define IDC_ABDICATE                    1205
#define IDC_CHECK_F8                    1206
#define IDC_CHECK_F9                    1207
#define IDC_CHECK_F10                   1208
#define IDC_RENOUNCE                    1208
#define IDC_CHECK_F11                   1209
#define IDC_ABDICATENAME                1209
#define IDC_CHECK_F12                   1210
#define IDC_VOTENAME                    1211
#define IDC_EXILE                       1212
#define IDC_RANK                        1213
#define IDC_CURRENTVOTE                 1214
#define IDC_GUILDNAME                   1215
#define IDC_MRANK1                      1216
#define IDC_MRANK2                      1217
#define IDC_MRANK3                      1218
#define IDC_MRANK4                      1219
#define IDC_MRANK5                      1220
#define IDC_SECRET                      1221
#define IDC_FRANK1                      1222
#define IDC_FRANK2                      1223
#define IDC_RANKDISPLAY                 1223
#define IDC_FRANK3                      1224
#define IDC_DISBAND                     1224
#define IDC_FRANK4                      1225
#define IDC_ALLYGUILDS                  1225
#define IDC_FRANK5                      1226
#define IDC_GUILDS                      1226
#define IDC_ENEMYGUILDS                 1227
#define IDC_UNALLY                      1228
#define IDC_ENEMY                       1229
#define IDC_ALLY                        1230
#define IDC_UNENEMY                     1231
#define IDC_GUILDSTATUS                 1232
#define IDC_ABANDON                     1235
#define IDC_ALLYLABEL                   1236
#define IDC_GUILD_COST                  1237
#define IDC_GUILD_PASSWORD              1239
#define IDC_NOHALL                      1241
#define IDC_LABEL                       1242
#define IDC_GROUPS                      1243
#define IDC_DELGROUP                    1244
#define IDC_GROUPMEMBERS                1245
#define IDC_LOGGEDON                    1246
#define IDC_ADDMEMBER                   1247
#define IDC_DELMEMBER                   1249
#define IDC_ADDNAME                     1250
#define IDC_NEWGROUP                    1251
#define IDC_NEWGROUPTEXT                1252
#define IDC_ADDNAMETEXT                 1253
#define IDC_GROUP_DONE                  1254
#define IDC_EDIT3                       1255
#define IDC_GROUPTELL                   1255
#define IDC_GROUPSTATUS                 1256
#define IDC_VERB                        1260
#define IDC_SUICIDE_PASSWORD            1260
#define IDC_EXPANSION                   1261
#define IDC_COMMAND_LIST                1263
#define IDC_TUNNEL                      1264
#define IDC_MINIMAP                     1265
#define IDC_ACCEPT                      1265
#define IDC_STATIC_NOACCEPT             1266
#define IDC_STATIC_GUILD                1266
#define ID_SPELL                        3065
#define IDM_WHO                         4000
#define IDM_ALIAS                       4001
#define IDM_GUILD                       4002
#define IDM_WAVE                        4003
#define IDM_POINT                       4004
#define IDM_NEUTRAL                     4005
#define IDM_HAPPY                       4006
#define IDM_SAD                         4007
#define IDM_WRY                         4008
#define IDM_GROUP                       4009
#define IDM_VERBALIAS                   4010
#define IDM_DANCE                       4011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1267
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
