#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\towns.bof
BOFS  = barlqtwn.bof crnthtwn.bof jasprtwn.bof marntwn.bof tostwn.bof hazartwn.bof \
                kocatwn.bof wanderer.bof goad.bof decoratr.bof ladyphen.bof

!include $(KODDIR)\kod.mak
