# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = ratsold.bgf ratsoldX.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\ratsold.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\ratsoldX.bgf 2>nul
