#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\profic.bof
BOFS = profswrd.bof profmace.bof profscim.bof brawling.bof profhamr.bof \
        profaxe.bof archery.bof profshsw.bof proffalc.bof

!include $(KODDIR)\kod.mak
