#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\dmspell.bof

BOFS = damn.bof pardon.bof dmrescue.bof page.bof bonk.bof scry.bof armag.bof \
       villify.bof insight.bof evaluate.bof dmhold.bof squelch.bof \
       spectate.bof

!include $(KODDIR)\kod.mak
