#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\jonasmurderqt.bof
BOFS = jonasmurderoneqt.bof jonasmurdertwoqt.bof jonasmurderthreeqt.bof

!include $(KODDIR)\kod.mak
