#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\gemspellpower.bof
BOFS = gemshalillepower.bof gemqorpower.bof gemkraananpower.bof gemriijapower.bof gemjalapower.bof gemfarenpower.bof

!include $(KODDIR)\kod.mak