#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\monsroom.bof

BOFS =  badland1.bof a5.bof a6.bof c4.bof c6.bof castle1b.bof d4.bof \
	 d5.bof e2.bof e4.bof e5.bof e7.bof f2.bof f3.bof f4.bof f6.bof f7.bof forest2.bof forest3.bof \
         forest4.bof g4.bof g5.bof g6.bof g7.bof g8.bof g9.bof h3.bof h5.bof \
	 h6.bof h7.bof h8.bof i3.bof i6.bof i7.bof i8.bof i9.bof nest1.bof \
	 objroom.bof throne1.bof toscrypt.bof tosgrave.bof \
         uworld.bof d6.bof d7.bof f8.bof barlsew.bof j3.bof feyforst.bof \
         guest6.bof barlsew2.bof barlsew3.bof jassew1.bof jassew2.bof jassew3.bof \
         orccave1.bof orccave2.bof orccave3.bof orccave4.bof orccave5.bof \
         orccave6.bof orcpita.bof orcpitb.bof kocsew1.bof kocsew2.bof bossroom.bof \
         kcforest.bof orccav1x.bof orccav5x.bof lichmaze.bof necarea1.bof necarea2.bof \
         necarea3.bof necare3a.bof necare3b.bof necarea4.bof necarea5.bof \
         marcryp1.bof marcryp2.bof oldjas.bof oldmar.bof oldbarln.bof oldbarls.bof \
         marcry3a.bof castle2b.bof castle2c.bof throne2.bof


#       g7.bof h8.bof i2.bof i4.bof i5.bof \
#       j4.bof j5.bof j6.bof j7.bof j8.bof j9.bof k3.bof \
#       k4.bof k5.bof k6.bof k7.bof k8.bof l2.bof l3.bof l4.bof l5.bof l6.bof \
#       l7.bof l8.bof m1.bof m2.bof m3.bof m4.bof m5.bof m6.bof m7.bof m8.bof \
#       n1.bof n2.bof n3.bof n4.bof n5.bof n6.bof n7.bof n8.bof o1.bof \
#       o2.bof o3.bof o4.bof

!include $(KODDIR)\kod.mak

