#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\reagent.bof
BOFS = mushroom.bof mushb.bof mushp.bof mushr.bof \
        herbs.bof elderbry.bof orctooth.bof bdrgscal.bof \
	dangfeth.bof farywing.bof diamond.bof emerald.bof sapphire.bof \
        ruby.bof entberry.bof firesand.bof dflyeye.bof kripclaw.bof \
        solagh.bof rnbwfern.bof uncserpm.bof webmass.bof shamblod.bof \
        polserpm.bof yrxlsap.bof webmoss.bof mushgray.bof mushgreen.bof mushyellow.bof \
        mushcyan.bof

!include $(KODDIR)\kod.mak
