#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\potion.bof
BOFS = purifyp.bof rmcursep.bof curepsnp.bof curedisp.bof \
	shadowp.bof anonp.bof baitp.bof nodebrsp.bof deflectp.bof \
	mshieldp.bof respoisp.bof rescoldp.bof resfirep.bof resmagcp.bof \
	resshckp.bof denialp.bof karaholp.bof nightvp.bof hastep.bof \
	strengtp.bof detgoodp.bof detevilp.bof detinvip.bof feigndp.bof \
	resacidp.bof cloakp.bof freeactp.bof rescuep.bof eageyep.bof

!include $(KODDIR)\kod.mak
