# makefile for textures

TOPDIR=..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = $(TOPDIR)\resource\textures

.SUFFIXES: .bmp

BGFS = \
	$(OUTDIR)\grd20121.bgf \
	$(OUTDIR)\grd20122.bgf \
	$(OUTDIR)\grd20124.bgf \
	$(OUTDIR)\grd20125.bgf \
	$(OUTDIR)\grd20126.bgf \
	$(OUTDIR)\grd20127.bgf \
	$(OUTDIR)\grd20128.bgf \
	$(OUTDIR)\grd20129.bgf \
	$(OUTDIR)\grd20130.bgf \
	$(OUTDIR)\grd20200.bgf \
	$(OUTDIR)\grd20201.bgf \
	$(OUTDIR)\grd20202.bgf \
	$(OUTDIR)\grd20203.bgf \
	$(OUTDIR)\grd20204.bgf \
	$(OUTDIR)\grd20205.bgf \
	$(OUTDIR)\grd20206.bgf \
	$(OUTDIR)\grd20207.bgf \
	$(OUTDIR)\grd20208.bgf \
	$(OUTDIR)\grd20209.bgf \
	$(OUTDIR)\grd20210.bgf \
	$(OUTDIR)\grd20211.bgf \
	$(OUTDIR)\grd20212.bgf \
	$(OUTDIR)\grd20213.bgf \
	$(OUTDIR)\grd20214.bgf \
	$(OUTDIR)\grd20215.bgf \
	$(OUTDIR)\grd20216.bgf \
	$(OUTDIR)\grd20217.bgf \
	$(OUTDIR)\grd20218.bgf \
	$(OUTDIR)\grd20219.bgf \
	$(OUTDIR)\grd20220.bgf \
	$(OUTDIR)\grd20221.bgf \
	$(OUTDIR)\grd20222.bgf \
	$(OUTDIR)\grd20223.bgf \
	$(OUTDIR)\grd20224.bgf \
	$(OUTDIR)\grd20225.bgf \
	$(OUTDIR)\grd20226.bgf \
	$(OUTDIR)\grd20227.bgf \
	$(OUTDIR)\grd20228.bgf \
	$(OUTDIR)\grd20229.bgf \

all: makedirs $(BGFS)

{$(SOURCEDIR)}.bmp.bgf:
	$(MAKEBGF) -o $@ -n "Unnamed $*" 1 $< 1 1 1

# bitmaps for walls, ceilings, and floors

$(OUTDIR)\grd20121.bgf:
	$(MAKEBGF) -o $@ -n "tosin-base-floor" -s 8 1 $** 1 1 1

$(OUTDIR)\grd20122.bgf:
	$(MAKEBGF) -o $@ -n "tosin-base-ceil" -s 1 1 $** 1 1 1

$(OUTDIR)\grd20124.bgf:
	$(MAKEBGF) -o $@ -n "tos inn h" -s 2 1 $** 1 1 1

$(OUTDIR)\grd20125.bgf:
	$(MAKEBGF) -o $@ -n "tos inn i floor" -s 1 1 $** 1 1 1

$(OUTDIR)\grd20126.bgf:
	$(MAKEBGF) -o $@ -n "tos-escape-tunnel-w" -s 4 1 $** 1 1 1

$(OUTDIR)\grd20127.bgf:
	$(MAKEBGF) -o $@ -n "tos-escape-tunnel-w2" -s 4 1 $** 1 1 1

$(OUTDIR)\grd20128.bgf:
	$(MAKEBGF) -o $@ -n "tos-escape-tunnel-door" -s 4 1 $** 1 1 1

$(OUTDIR)\grd20129.bgf:
	$(MAKEBGF) -o $@ -n "tos-escape-tunnel-w3" -s 4 1 $** 1 1 1

$(OUTDIR)\grd20130.bgf:
	$(MAKEBGF) -o $@ -n "mudroot" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20200.bgf:
	$(MAKEBGF) -o $@ -n "east-stonewall" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20201.bgf:
	$(MAKEBGF) -o $@ -n "east-grass" -s 1 1 $** 1 1 1
	
$(OUTDIR)\grd20202.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-gravel" -s 1 1 $** 1 1 1
	
$(OUTDIR)\grd20203.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-bench-sides" -s 2 1 $** 1 1 1
	
$(OUTDIR)\grd20204.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-bench-top" -s 1 1 $** 1 1 1
	
$(OUTDIR)\grd20205.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-fountainwall" -s 3 1 $** 1 1 1
	
$(OUTDIR)\grd20206.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-fountaincenter" -s 8 1 $** 1 1 1
	
$(OUTDIR)\grd20207.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-firepit" -s 4 1 $** 1 1 1

$(OUTDIR)\grd20208.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building1-wall1" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20209.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building1-roof" -s 2 1 $** 1 1 1
	
$(OUTDIR)\grd20210.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building1-door" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20211.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building1-wall2" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20212.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building1-wall3" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20213.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-sign" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20214.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall1" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20215.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall2" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20216.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall3" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20217.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall4" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20218.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall5" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20219.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-roof" -s 2 1 $** 1 1 1
	
$(OUTDIR)\grd20220.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall6" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20221.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building2-wall7" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20222.bgf:
	$(MAKEBGF) -o $@ -n "east-fence" -s 8 1 $** 1 1 1
	
$(OUTDIR)\grd20223.bgf:
	$(MAKEBGF) -o $@ -n "east-stone-ceiling" -s 1 1 $** 1 1 1
	
$(OUTDIR)\grd20224.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building3-wall1" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20225.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building3-roof" -s 1 1 $** 1 1 1	
	
$(OUTDIR)\grd20226.bgf:
	$(MAKEBGF) -o $@ -n "east-jixa-building3-wall2" -s 4 1 $** 1 1 1
	
$(OUTDIR)\grd20227.bgf:
	$(MAKEBGF) -o $@ -n "east-brick-halfivy" -s 4 1 $** 1 1 1	

$(OUTDIR)\grd20228.bgf:
	$(MAKEBGF) -o $@ -n "east-brick-ivy" -s 1 1 $** 1 1 1
	
$(OUTDIR)\grd20229.bgf:
	$(MAKEBGF) -o $@ -n "east-ironfence" -s 8 1 $** 1 1 1

	
!include $(TOPDIR)\rules.mak
