//
// CoolPrj
//
/// \file version.h
/// Library version and build information header
//
// Copyright (c) 2013 Vidar Hasfjord
// See OWLNext for license information (http://owlnext.sourceforge.net).

#if !defined(COOLPRJ_VERSION_H)
#define COOLPRJ_VERSION_H

#include <owl/version.h>

// Create aliases for OWL version macros
//
#define COOLPRJ_PRERELEASE OWL_PRERELEASE
#define COOLPRJ_FILEVERSION OWL_FILEVERSION
#define COOLPRJ_PRODUCTVERSION OWL_PRODUCTVERSION
#define COOLPRJ_FILEVERSION_STRING OWL_FILEVERSION_STRING
#define COOLPRJ_PRODUCTVERSION_STRING OWL_PRODUCTVERSION_STRING
#define COOLPRJ_VERSION_16BIT OWL_VERSION_16BIT
#define COOLPRJ_VERSION_32BIT OWL_VERSION_32BIT
#define COOLPRJ_VERSION_64BIT OWL_VERSION_64BIT
#define COOLPRJ_BUILD_REVISION OWL_BUILD_REVISION
#define COOLPRJ_BUILD_REVISION_DATE OWL_BUILD_REVISION_DATE
#define COOLPRJ_BUILD_DATE OWL_BUILD_DATE
#define COOLPRJ_BUILD_MIXED OWL_BUILD_MIXED
#define COOLPRJ_BUILD_DIRTY OWL_BUILD_DIRTY

#endif  //  COOLPRJ_VERSION_H
