#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\tosrm.bof

BOFS =  tos.bof easttos.bof \
	tosapoth.bof tosarena.bof tosaren2.bof tosbank.bof tosgrey.bof \
	toshall.bof tossmith.bof tostan.bof toslover.bof tosforgt.bof \
   toshidden.bof tostavern.bof toscellar.bof

!include $(KODDIR)\kod.mak

