#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\pforget.bof
BOFS = forgetsk.bof forgetfr.bof forgetsh.bof forgetkr.bof forgetqr.bof \
	forgetrj.bof forgetjl.bof

!include $(KODDIR)\kod.mak
