#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\hinder.bof
BOFS = truth.bof civility.bof concil.bof sacrdres.bof profnres.bof disharm.bof

!include $(KODDIR)\kod.mak
