# Makefile for intro DLL

TOPDIR=..\..
!include $(TOPDIR)\common.mak

MODULE = intro

!include $(MODULEDIR)\module.mak

$(OUTDIR)\intro.dll: \
        $(OUTDIR)\intro.obj \
        $(OUTDIR)\intro.res

!include $(TOPDIR)\rules.mak
