# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = gift1.bgf gift2.bgf gift3.bgf gift4.bgf

!include $(RESOURCEDIR)\copy.mak

!include $(TOPDIR)\rules.mak
