# Makefile 

TOPDIR=..\..\..\..
!include $(TOPDIR)\common.mak

SOURCEDIR = .

BGFS = gift1.bgf gift2.bgf gift3.bgf gift4.bgf

!include $(RESOURCEDIR)\copy.mak

clean:
	@$(RM) $(CLIENTRUNDIR)\resource\gift1.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\gift2.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\gift3.bgf 2>nul
	@$(RM) $(CLIENTRUNDIR)\resource\gift4.bgf 2>nul
